In [1]:
import pandas as pd
from geopy import distance
pd.set_option('display.max_columns', None)
import numpy as np

In [1]:
# pwd # how to check working directory

'/Users/amba/Documents/GitHub/UMR-TDA-2021/pools EDA/AL'

In [389]:
filePath = "../pool data/ltrm_water_data_lat_long.csv"
water20 = pd.read_csv(filePath, low_memory = False)
print("dataFrame Made")

dataFrame Made


In [4]:
# filter for pool 26
dataFrame = water20[water20['FLDNUM'] == 4]
print(dataFrame.shape)
dataFrame.head()

(30088, 133)


SHEETBAR  FLDNUM        DATE   TIME  NSAMPLES PROJCD  LOCATCD DATABLCK  \
11168  -4404083       4  06/18/1993  09:40       NaN     M-  CA00.4M  W149306   
11169  -4404082       4  06/18/1993  09:23       NaN     M-  M193.2F  W149306   
11170  -4404081       4  06/18/1993  09:08       NaN     M-  MO02.0X  W149306   
11171  -4404080       4  06/18/1993  08:56       NaN     M-  M196.9Q  W149306   
11172  -4404079       4  06/18/1993  08:35       NaN     M-  WD00.2M  W149306   

       WAVHI  WAVEHIQF   WDP  ZMAX ZMAXQF  SECCHI SECCHIQF  WAVCD  ZICE  \
11168    1.0       NaN   5.8   5.8    NaN    36.0      NaN    NaN   0.0   
11169    6.0       NaN  11.3  11.3    NaN     3.0      NaN    NaN   0.0   
11170    3.0       NaN  11.6  11.6    NaN     4.0      NaN    NaN   0.0   
11171    7.0       NaN   8.8   8.8    NaN    19.0      NaN    NaN   0.0   
11172    2.0       NaN   4.3   4.3    NaN    46.0      NaN    NaN   0.0   

      ZICEQF  ZSICE ZSICEQF  PICE PICEQF  ZSNOW ZSNOWQF  PSNOW PSNOWQF  \
11168    NaN    NaN     NaN   0.0    NaN    0.0     NaN    0.0     NaN   
11169    NaN    NaN     NaN   0.0    NaN    0.0     NaN    0.0     NaN   
11170    NaN    NaN     NaN   0.0    NaN    0.0     NaN    0.0     NaN   
11171    NaN    NaN     NaN   0.0    NaN    0.0     NaN    0.0     NaN   
11172    NaN    NaN     NaN   0.0    NaN    0.0     NaN    0.0     NaN   

       SITETYPE  STRATUM  SUMCD  SBSTRATE  VEGCOVER  VEGDENS VEGTYPE  METHOD  \
11168         2      NaN    NaN       NaN       NaN      NaN     NaN     NaN   
11169         2      NaN    NaN       NaN       NaN      NaN     NaN     NaN   
11170         2      NaN    NaN       NaN       NaN      NaN     NaN     NaN   
11171         2      NaN    NaN       NaN       NaN      NaN     NaN     NaN   
11172         2      NaN    NaN       NaN       NaN      NaN     NaN     NaN   

       UTMZONE   NORTHING   EASTING     GRIDCODE   Z15NORTH   Z15EAST  \
11168       15  4299188.0  751312.0  75135.29900  4299188.0  751312.0   
11169       15  4297585.0  748732.0  74875.29735  4297585.0  748732.0   
11170       15  4301868.0  748261.0  74830.30165  4301868.0  748261.0   
11171       15  4302266.0  750615.0  75065.30205  4302266.0  750615.0   
11172       15  4305532.0  749089.0  74910.30530  4305532.0  749089.0   

       FLDEAST  FLDNORTH  DRVEAST  DRVNORTH  ACCURACY  SAMPTYPE  STAGE  \
11168      NaN       NaN      NaN       NaN       NaN       NaN    NaN   
11169      NaN       NaN      NaN       NaN       NaN       NaN    NaN   
11170      NaN       NaN      NaN       NaN       NaN       NaN    NaN   
11171      NaN       NaN      NaN       NaN       NaN       NaN    NaN   
11172      NaN       NaN      NaN       NaN       NaN       NaN    NaN   

       RCRDCODE LDRCODE  ROWNUM    Z  ZQF SAMPZCD CALCZCD  TEMP TEMPQF   DO  \
11168       NaN     NaN     NaN  0.2  NaN      SF      SF  25.5    NaN  9.8   
11169       NaN     NaN     NaN  0.2  NaN      SF      SF  25.0    NaN  6.2   
11170       NaN     NaN     NaN  0.2  NaN      SF      SF  24.9    NaN  6.2   
11171       NaN     NaN     NaN  0.2  NaN      SF      SF  23.8    NaN  6.8   
11172       NaN     NaN     NaN  0.2  NaN      SF      SF  25.5    NaN  9.2   

      DOQF    PH PHQF   TURB TURBQF   COND CONDQF  VEL VELQF  DIR DIRQF  \
11168  NaN  8.45  NaN   24.0    NaN  586.0    NaN  NaN   NaN  NaN   NaN   
11169  NaN  8.03  NaN  600.0    NaN  514.0    NaN  NaN   NaN  NaN   NaN   
11170  NaN  8.04  NaN  457.0    NaN  516.0    NaN  NaN   NaN  NaN   NaN   
11171  NaN  8.24  NaN   79.0    NaN  429.0    NaN  NaN   NaN  NaN   NaN   
11172  NaN  8.41  NaN   17.0    NaN  699.0    NaN  NaN   NaN  NaN   NaN   

       SMPLBAR  SNPCODE NOXCODE METCODE CLCODE SSCODE CHSCODE CHFCODE PYTCODE  \
11168      NaN      NaN     NaN     NaN    NaN    NaN     NaN     NaN     NaN   
11169      NaN      NaN     NaN     NaN    NaN    NaN     NaN     NaN     NaN   
11170      NaN      NaN     NaN     NaN    NaN    NaN     NaN     NaN     NaN   
11171    

In [5]:
dummyData = dataFrame.head()
dummyData = dummyData[["LATITUDE", "LONGITUDE", "TP"]]

print(dummyData)

        LATITUDE  LONGITUDE     TP
11168  38.805639 -90.105906  0.104
11169  38.791944 -90.136160  0.266
11170  38.830625 -90.140035  0.255
11171  38.833540 -90.112804  0.167
11172  38.863368 -90.129181  0.146


In [6]:
def Distance(row1, row2):
    #print(row1.LATITUDE)
    #print(row1.LONGITUDE)
    #print(row2.LATITUDE)
    #print(row2.LONGITUDE)
    series1 =(row1.LATITUDE, row1.LONGITUDE)
    series2 = (row2.LATITUDE, row2.LONGITUDE)
    dist = distance.distance(series1, series2).km
    return dist

def fillMatrix(df):
    dist_matrix = np.zeros((df.shape[0],df.shape[0]))
#     row1Index = df.iloc[0]
#     #print(row1Index)
#     for index, row in df.iterrows():
#         dist_matrix[]
    size = dist_matrix.size
    #print("size = " + str(size))
    for i in range(0, df.shape[0]):
        #print("i = " + str(i))
        #print("\n")
        loc_i = df.iloc[i]
        for j in range(i+1, df.shape[0]):
            #print("j = " + str(j))
            loc_j = df.iloc[j]
            dist_matrix[i,j] = Distance(loc_i, loc_j)
            dist_matrix[j,i] = dist_matrix[i,j]
    return dist_matrix
    

    



In [6]:
print(dummyData[0:1])
print(dummyData.shape)
print(dummyData)
row1 = pd.Series(dummyData.iloc[0])
row2 = pd.Series(dummyData.iloc[1])

print(Distance(row1, row2))
print("-------------")
print(dummyData.shape)
print(fillMatrix(dummyData))
print("Done")


        LATITUDE  LONGITUDE     TP
11168  38.805639 -90.105906  0.104
(5, 3)
        LATITUDE  LONGITUDE     TP
11168  38.805639 -90.105906  0.104
11169  38.791944 -90.136160  0.266
11170  38.830625 -90.140035  0.255
11171  38.833540 -90.112804  0.167
11172  38.863368 -90.129181  0.146
3.036311919399564
-------------
(5, 3)
[[0.         3.03631192 4.05941553 3.15474465 6.71971392]
 [3.03631192 0.         4.30726734 5.04368347 7.95212814]
 [4.05941553 4.30726734 0.         2.38653466 3.75503441]
 [3.15474465 5.04368347 2.38653466 0.         3.60358857]
 [6.71971392 7.95212814 3.75503441 3.60358857 0.        ]]
Done


In [213]:
dummyData = dataFrame.head()
dummyData = dummyData.reset_index(drop = True)
dummyData = dummyData[["LATITUDE", "LONGITUDE", "TP"]]

dummyData.loc[0, "TP"] = None
dummyData.loc[2, "TP"] = None
print(dummyData)
dummyDist = fillMatrix(dummyData)

print(dummyDist)



    LATITUDE  LONGITUDE     TP
0  38.805639 -90.105906    NaN
1  38.791944 -90.136160  0.266
2  38.830625 -90.140035    NaN
3  38.833540 -90.112804  0.167
4  38.863368 -90.129181  0.146
[[0.         3.03631192 4.05941553 3.15474465 6.71971392]
 [3.03631192 0.         4.30726734 5.04368347 7.95212814]
 [4.05941553 4.30726734 0.         2.38653466 3.75503441]
 [3.15474465 5.04368347 2.38653466 0.         3.60358857]
 [6.71971392 7.95212814 3.75503441 3.60358857 0.        ]]


In [224]:
"""
Dist_matrix = fillMatrix
Create new data column called Predicted TP, starting as a duplicated TP column
for each row:
    if TP = NaN:
        get TP distance Matrix Row 
        get minimum two non NaN distances, called d_{i,j} d_{i,k}
        predicted_TP = TP_j * ((1/(d_{i,j})) / ((1/d_{i,j}) + (1/d_{i,k}))) + TP_k * ((1/(d_{i,k})) / ((1/d_{i,j}) + (1/d_{i,k}))) 
        
    Else:
        continue 


"""

def getNearest(index, copy_dist, n):
    # returns list of list
    ## first list gives distance to interpolation point
    ## second list gives indices of the original df
    rowInQuestion = copy_dist[index]
    
    idx = np.argpartition(rowInQuestion, 2)
    n_dist = rowInQuestion[idx[:n]].flatten()
    # length n, the least distances of rowInQuestion
    
#     print("the n least distances are")
#     print(n_min_dist)
    
    idx_of_nearest = list() # length n, idx (for df) of the nearest locations (rows) 
    
    for dist in n_dist:
        idx = np.where(rowInQuestion == dist)[0][0]
        idx_of_nearest.append(idx)
        
#     print("gives n indices (of original df) for the locations of least distances")
#     print(idx_of_nearest)
    
    return([n_dist, idx_of_nearest])

def getInterpolation(distances_array, values_list):
    interpolate_value = 0
    denominator = sum(1 / distances_array)
    
    for term in range(len(values_list)):
        interpolate_value += values_list[term]/distances_array[term]
        
    interpolate_value = interpolate_value/denominator
    
    return(interpolation)

def predict(df, dist_matrix, naVar, n):
    # df is re-indexed
    # n is the number of points (closest location) we are interpolating with 
    
    # goal: predict the missing values of naVar
    interp_col = "PREDICTED_" + naVar
    df[interp_col] = df[naVar]
    
#     for n_location in range(1, n+1):
        
#         df[naVar + "_" + str(nearest_location) + "_value"] = 0
#         # values of naVar to interpolate with
        
#         df[naVar + "_" + str(nearest_location) + "_dist"] = 0
#         # distance between current row and nearest_location to interpolate with
        
    copy_dist = np.copy(dist_matrix)
    
    naIndices = np.argwhere(np.isnan(np.array(df[naVar]))) 
    # retrieve indices with missing values of naVar
    
    copy_dist[:, naIndices] = None 
    # column with missing naVar values can't be used for interpolation
    
    # df.loc[np.ndarray.flatten(naIndices), :]
    ## this gives the rows of the df with missing values in naVar
    
    for locations_to_interpolate in naIndices:
        nearest_dist_idx = getNearest(locations_to_interpolate[0], copy_dist, n) # length n
        nearest_naVar_val = getnaVarValue()

        print(nearest)
#         for n_location in range(0, n): # n is the number of locations to interpolate with
            
#             min_idx = n_nearest_idx[n_location] # index for df
#             naVar_col = naVar + "_" + str(n_location+1) + "_value"
#             dist_col = naVar + "_" + str(n_location+1) + "_dist"
            
#             df.loc[locations_to_interpolate, naVar_col] = df.loc[min_idx, naVar]
#             df.loc[locations_to_interpolate, dist_col] = dist_matrix[locations_to_interpolate, min_idx]
            
#             print(n_idx)
#             print(df)
        
#         df.loc[locations_to_interpolate, interp_col] = getInterpolation(df.loc[locations_to_interpolate, naVar_col], 
#                                                      df.loc[locations_to_interpolate, naVar_col],
#                                                      df.loc[locations_to_interpolate, dist_col], 
#                                                      df.loc[locations_to_interpolate, dist_col])
        
    return df

In [225]:
print(predict(dummyData, dummyDist, "TP", 2))
print("-------")
print(dummyDist)



[array([3.03631192, 3.15474465]), [1, 3]]
[array([2.38653466, 3.75503441]), [3, 4]]
    LATITUDE  LONGITUDE     TP  PREDICTED_TP  TP_1_value  TP_1_dist  \
0  38.805639 -90.105906    NaN           NaN       0.266   3.036312   
1  38.791944 -90.136160  0.266         0.266       0.000   0.000000   
2  38.830625 -90.140035    NaN           NaN       0.167   2.386535   
3  38.833540 -90.112804  0.167         0.167       0.000   0.000000   
4  38.863368 -90.129181  0.146         0.146       0.000   0.000000   

   TP_2_value  TP_2_dist  
0       0.167   3.154745  
1       0.000   0.000000  
2       0.146   3.755034  
3       0.000   0.000000  
4       0.000   0.000000  
-------
[[0.         3.03631192 4.05941553 3.15474465 6.71971392]
 [3.03631192 0.         4.30726734 5.04368347 7.95212814]
 [4.05941553 4.30726734 0.         2.38653466 3.75503441]
 [3.15474465 5.04368347 2.38653466 0.         3.60358857]
 [6.71971392 7.95212814 3.75503441 3.60358857 0.        ]]


In [237]:
np.array([3.03631192, 3.15474465])[1]

3.15474465

In [232]:
print(str(1/3.03631192))
print(str(1/3.15474465))
print(str(1/3.03631192 + 1/3.15474465))

0.3293469269125683
0.3169828657923233
0.6463297927048917


# Trying to merge duplicates scratch

In [390]:
water_var = ['LATITUDE', 'LONGITUDE', 'SHEETBAR', 'DATE'
             'TN','TP','TEMP','DO','TURB',
             'COND','VEL','SS','WDP','CHLcal','SECCHI']

# water20 = water20.reset_index() # reset index, makes a column out of SHEETBAR


In [391]:
water20sub = water20.filter(items=water_var).head(100)
water20sub

LATITUDE  LONGITUDE  SHEETBAR     TP  TEMP    DO   TURB   COND   VEL  \
0   39.939235 -90.533462  -4604348  0.471  23.0   6.9  225.0  600.0   NaN   
1   40.064462 -90.146572  -4604347  0.265  22.2   7.4  387.0  467.0   NaN   
2   40.064462 -90.146572  -4604347    NaN  22.2   7.5  380.0  470.0   NaN   
3   40.215057 -90.140225  -4604346  0.360  23.0   7.0  200.0  640.0  0.61   
4   40.215057 -90.140225  -4604346    NaN  23.0   6.9  270.0  643.0  0.42   
..        ...        ...       ...    ...   ...   ...    ...    ...   ...   
95  40.316217 -90.068509  -4604296    NaN  10.5   9.3   31.0  630.0  0.32   
96  40.305700 -90.074364  -4604295  0.211  10.0  10.5   55.0  626.0  0.48   
97  40.305700 -90.074364  -4604295    NaN  10.0  10.4   69.0  638.0  0.21   
98  40.158490 -90.202874  -4604294  0.288  10.8   8.6   48.0  618.0  0.24   
99  40.158490 -90.202874  -4604294    NaN  10.9   8.5   47.0  616.0  0.38   

       SS  WDP  CHLcal  SECCHI  
0   337.5  7.0     NaN    11.0  
1   447.1  5.0     NaN     5.0  
2     NaN  5.0     NaN     5.0  
3   232.8  4.8     NaN    10.0  
4     NaN  4.8     NaN    10.0  
..    ...  ...     ...     ...  
95    NaN  5.1     NaN    40.0  
96  112.0  6.7     NaN    30.0  
97    NaN  6.7     NaN    30.0  
98   33.4  5.0     NaN    28.0  
99    NaN  5.0     NaN    28.0  

[100 rows x 13 columns]

In [392]:
dup_count = pd.DataFrame(water20sub.groupby("SHEETBAR").size(), 
                         columns = ['count']).reset_index()
# df['size'] = df.groupby(['A','B']).transform(np.size)
dup_count

SHEETBAR  count
0   -4604348      1
1   -4604347      2
2   -4604346      2
3   -4604345      2
4   -4604344      1
5   -4604343      2
6   -4604342      1
7   -4604341      2
8   -4604340      1
9   -4604339      2
10  -4604338      1
11  -4604337      2
12  -4604336      2
13  -4604335      2
14  -4604334      2
15  -4604333      2
16  -4604332      1
17  -4604331      2
18  -4604330      2
19  -4604329      2
20  -4604328      1
21  -4604327      2
22  -4604326      2
23  -4604325      2
24  -4604324      2
25  -4604323      2
26  -4604322      2
27  -4604321      2
28  -4604320      2
29  -4604319      1
30  -4604318      2
31  -4604317      2
32  -4604316      2
33  -4604315      2
34  -4604314      2
35  -4604313      2
36  -4604312      2
37  -4604311      1
38  -4604310      2
39  -4604309      2
40  -4604308      1
41  -4604307      2
42  -4604306      2
43  -4604305      2
44  -4604304      2
45  -4604303      2
46  -4604302      2
47  -4604301      2
48  -4604300      2
49  -4604299      2
50  -4604298      2
51  -4604297      2
52  -4604296      2
53  -4604295      2
54  -4604294      2

In [393]:
dup_count = dup_count[dup_count['count'] > 1] # filtering
dup_count

SHEETBAR  count
1   -4604347      2
2   -4604346      2
3   -4604345      2
5   -4604343      2
7   -4604341      2
9   -4604339      2
11  -4604337      2
12  -4604336      2
13  -4604335      2
14  -4604334      2
15  -4604333      2
17  -4604331      2
18  -4604330      2
19  -4604329      2
21  -4604327      2
22  -4604326      2
23  -4604325      2
24  -4604324      2
25  -4604323      2
26  -4604322      2
27  -4604321      2
28  -4604320      2
30  -4604318      2
31  -4604317      2
32  -4604316      2
33  -4604315      2
34  -4604314      2
35  -4604313      2
36  -4604312      2
38  -4604310      2
39  -4604309      2
41  -4604307      2
42  -4604306      2
43  -4604305      2
44  -4604304      2
45  -4604303      2
46  -4604302      2
47  -4604301      2
48  -4604300      2
49  -4604299      2
50  -4604298      2
51  -4604297      2
52  -4604296      2
53  -4604295      2
54  -4604294      2

In [409]:
water20dup = water20sub[pd.Series(water20sub["SHEETBAR"]).
                        isin(dup_count["SHEETBAR"])]
# use boolean filtering to subset 

water20dup

LATITUDE  LONGITUDE  SHEETBAR     TP  TEMP    DO   TURB   COND   VEL  \
1   40.064462 -90.146572  -4604347  0.265  22.2   7.4  387.0  467.0   NaN   
2   40.064462 -90.146572  -4604347    NaN  22.2   7.5  380.0  470.0   NaN   
3   40.215057 -90.140225  -4604346  0.360  23.0   7.0  200.0  640.0  0.61   
4   40.215057 -90.140225  -4604346    NaN  23.0   6.9  270.0  643.0  0.42   
5   40.330350 -90.049078  -4604345  0.242  20.8   8.2   51.0  684.0  0.02   
..        ...        ...       ...    ...   ...   ...    ...    ...   ...   
95  40.316217 -90.068509  -4604296    NaN  10.5   9.3   31.0  630.0  0.32   
96  40.305700 -90.074364  -4604295  0.211  10.0  10.5   55.0  626.0  0.48   
97  40.305700 -90.074364  -4604295    NaN  10.0  10.4   69.0  638.0  0.21   
98  40.158490 -90.202874  -4604294  0.288  10.8   8.6   48.0  618.0  0.24   
99  40.158490 -90.202874  -4604294    NaN  10.9   8.5   47.0  616.0  0.38   

       SS  WDP  CHLcal  SECCHI  
1   447.1  5.0     NaN     5.0  
2     NaN  5.0     NaN     5.0  
3   232.8  4.8     NaN    10.0  
4     NaN  4.8     NaN    10.0  
5    54.7  2.3     NaN    22.0  
..    ...  ...     ...     ...  
95    NaN  5.1     NaN    40.0  
96  112.0  6.7     NaN    30.0  
97    NaN  6.7     NaN    30.0  
98   33.4  5.0     NaN    28.0  
99    NaN  5.0     NaN    28.0  

[90 rows x 13 columns]

In [410]:
water20sub[-pd.Series(water20sub["SHEETBAR"]).
           isin(dup_count["SHEETBAR"])].head() # non duplicates

LATITUDE  LONGITUDE  SHEETBAR     TP  TEMP   DO   TURB   COND  VEL  \
0   39.939235 -90.533462  -4604348  0.471  23.0  6.9  225.0  600.0  NaN   
7   40.316217 -90.068509  -4604344  0.290  20.2  8.0   64.0  699.0  NaN   
10  40.617643 -89.651818  -4604342  0.417  18.5  7.9  100.0  688.0  NaN   
13  40.325077 -89.956183  -4604340  0.122  16.0  8.2   18.0  584.0  NaN   
16  40.617643 -89.651818  -4604338  0.326  19.2  7.0   90.0  689.0  NaN   

       SS   WDP  CHLcal  SECCHI  
0   337.5   7.0     NaN    11.0  
7    86.8   5.0     NaN    18.0  
10  147.3  15.3     NaN     8.0  
13   24.5   0.4     NaN    -9.0  
16  109.5  18.0     NaN    16.0

LATITUDE  LONGITUDE  SHEETBAR     TP  TEMP    DO   TURB   COND   VEL  \
1   40.064462 -90.146572  -4604347  0.265  22.2   7.4  387.0  467.0   NaN   
2   40.064462 -90.146572  -4604347    NaN  22.2   7.5  380.0  470.0   NaN   
3   40.215057 -90.140225  -4604346  0.360  23.0   7.0  200.0  640.0  0.61   
4   40.215057 -90.140225  -4604346    NaN  23.0   6.9  270.0  643.0  0.42   
5   40.330350 -90.049078  -4604345  0.242  20.8   8.2   51.0  684.0  0.02   
..        ...        ...       ...    ...   ...   ...    ...    ...   ...   
95  40.316217 -90.068509  -4604296    NaN  10.5   9.3   31.0  630.0  0.32   
96  40.305700 -90.074364  -4604295  0.211  10.0  10.5   55.0  626.0  0.48   
97  40.305700 -90.074364  -4604295    NaN  10.0  10.4   69.0  638.0  0.21   
98  40.158490 -90.202874  -4604294  0.288  10.8   8.6   48.0  618.0  0.24   
99  40.158490 -90.202874  -4604294    NaN  10.9   8.5   47.0  616.0  0.38   

       SS  WDP  CHLcal  SECCHI  
1   447.1  5.0     NaN     5.0  
2     NaN  5.0     NaN     5.0  
3   232.8  4.8     NaN    10.0  
4     NaN  4.8     NaN    10.0  
5    54.7  2.3     NaN    22.0  
..    ...  ...     ...     ...  
95    NaN  5.1     NaN    40.0  
96  112.0  6.7     NaN    30.0  
97    NaN  6.7     NaN    30.0  
98   33.4  5.0     NaN    28.0  
99    NaN  5.0     NaN    28.0  

[90 rows x 13 columns]

In [385]:
dup_sheetbar = list()

for sheetbar in water20sub["SHEETBAR"]:
    if sheetbar in list(dup_count["SHEETBAR"]):
        dup_sheetbar.append(sheetbar)

In [387]:
len(dup_sheetbar)

90

In [349]:
water20sub[water20sub["SHEETBAR"] == -4604347]

LATITUDE  LONGITUDE  SHEETBAR    TN     TP  TEMP   DO   TURB   COND  VEL  \
1  40.064462 -90.146572  -4604347  7.49  0.265  22.2  7.4  387.0  467.0  NaN   
2  40.064462 -90.146572  -4604347   NaN    NaN  22.2  7.5  380.0  470.0  NaN   

      SS  WDP  CHLcal  SECCHI  
1  447.1  5.0     NaN     5.0  
2    NaN  5.0     NaN     5.0

In [319]:
water20sub[water20sub["SHEETBAR"] in ]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().